name: tsla_env
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - streamlit
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - pillow
    - zipp
    - altair
    - openpyxl
    - jupyter
    - ipykernel
    - xlrd
    - xlsxwriter
    - pip:
        - loguru